Show mount activation in detent doctor
When the build has a module that declares mounts, doctor has a
"mounts" row. It reads [mounts] activate_new_entries from
detent.toml. Off: new fstab entries take effect at the next boot or
mount. On with systemd: the mount units of new entries start after
an apply. On with another init system: a warning, because no mount
unit is started there.

Test first. Before the change the doctor tests did not compile:
  error[E0432]: unresolved import `super::mounts_check`

Item: Track D 1
Allows added: 0

Signed-off-by: Jauder Ho <jauderho@users.noreply.github.com>